# Generated by Django 5.2.4 on 2025-07-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('deadline', models.DateTimeField(verbose_name='截止日期')),
                ('priority', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=2, verbose_name='重要级')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['deadline'],
            },
        ),
    ]
